spring:
  application:
    name: blog
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: MY_BLOG
    password: 1234
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/example/blog/**/dao/mapper/*.xml